#! /usr/bin/env bash

function fixMyJavaInstall() {
	echo "$1"
	command -v update-alternatives
	local hasUpdateAlternatives
	hasUpdateAlternatives=$?
	for file in "$1"/bin/*
	do
		echo "$file"
		if [ -x "$file" ]
		then
			local filename
			filename=$(basename "$file")
			if [ $hasUpdateAlternatives -eq 0 ]; then
				command -v termux-setup-storage
				if [ $? -eq 1 ]; then
					sudo update-alternatives --install /usr/bin/"$filename" "$filename" "$file" 2000
                    sudo update-alternatives --set "$filename" "$file"
				else
					update-alternatives --install /usr/bin/"$filename" "$filename" "$file" 2000
					update-alternatives --set "$filename" "$file"
				fi
			else
				command -v termux-setup-storage
				if [ $? -eq 1 ]; then
					sudo ln -sf "$file" "/usr/bin/$filename"
				else
					ln -sf "$file" "/usr/bin/$filename"
				fi
			fi
			echo "$file" "$filename"
		fi
	done
}

fixMyJavaInstall "$@"