#! /usr/bin/env bash

function fixMyJavaInstall() {
	echo "$1"
	command -v update-alternatives
	local hasUpdateAlternatives
	hasUpdateAlternatives=$?
	command -v termux-setup-storage
	local isTermux
	isTermux=$?
	for file in "$1"/bin/*
	do
		echo "$file"
		if [ -x "$file" ]
		then
			local filename
			filename=$(basename "$file")
			if [ $isTermux -eq 1 ]; then
				if [ $hasUpdateAlternatives -eq 0 ]; then
					sudo update-alternatives --install "/usr/bin/$filename" "$filename" "$file" 2000
					sudo update-alternatives --set "$filename" "$file"
				else
					sudo ln -sf "$file" "usr/bin/$filename"
				fi
			else
				ln -sf "$file" "$TERMUX__PREFIX/bin/$filename"
			fi
			echo "$file" "$filename"
		fi
	done
}

fixMyJavaInstall "$@"